/**
 * The per-module battery, as source injected into the page.
 *
 * This is the producer the `DefectLedger` record type was written for and never
 * got: it visits one module and reports everything structurally wrong with it,
 * rather than stopping at the first failure the way a playthrough must.
 *
 * Three rules hold throughout, and each one is load-bearing:
 *
 *   1. **Every probe is individually guarded.** A module that throws in its
 *      creature pass must still get its door pass run. The whole point of a
 *      sweep is that one defect cannot shadow the ones behind it — that is the
 *      exact failure mode of the playthrough driver this complements.
 *   2. **A missing engine API is `skipped`, never a finding.** The battery
 *      reaches into engine internals that move. If `getName()` stops existing,
 *      the honest report is "this probe could not run", not 4,000 fabricated
 *      defects. Skips are counted and surfaced so a silently-dead probe cannot
 *      masquerade as a clean sweep.
 *   3. **Nothing is stringified.** THREE's `Texture.toJSON` warns for any
 *      texture it cannot encode and the engine hands textures to everything, so
 *      a single `JSON.stringify` of an engine object once produced ~30k console
 *      warnings inside the loop being measured. Findings carry names and
 *      numbers assembled by hand.
 */

/** Ceiling on findings of one code per module, so one systemic fault cannot fill the ledger. */
const PER_CODE_CAP = 25;

/**
 * How long to let a module settle after the engine calls it ready.
 *
 * `readyToProcessEvents` marks the end of LoadModule's success path, but models
 * and textures keep resolving on later frames. Probing on that instant reports
 * absences that fill themselves in moments later — false findings that would
 * bury the real ones.
 */
const DEFAULT_SETTLE_MS = 5000;

/**
 * Builds the probe expression for one module.
 *
 * @param {string} moduleName module to load, e.g. `101PER`
 * @param {object} options
 * @param {number} [options.loadTimeoutMs] how long to wait for the module to settle
 * @param {number} [options.frames] frames to render after load
 * @param {number} [options.perCodeCap] max findings per code
 * @returns {string} a JS expression evaluating to a Promise of the module report
 */
function buildModuleProbeSource(moduleName, options = {}) {
  const {
    loadTimeoutMs = 300000,
    frames = 30,
    perCodeCap = PER_CODE_CAP,
    settleMs = DEFAULT_SETTLE_MS,
  } = options;

  const NAME = JSON.stringify(moduleName);
  const TIMEOUT = Number(loadTimeoutMs);
  const FRAMES = Number(frames);
  const CAP = Number(perCodeCap);
  const SETTLE = Number(settleMs);

  return [
    '(async () => {',
    '  const NAME = ' + NAME + ';',
    '  const LOAD_TIMEOUT = ' + TIMEOUT + ';',
    '  const FRAMES = ' + FRAMES + ';',
    '  const CAP = ' + CAP + ';',
    '  const SETTLE_MS = ' + SETTLE + ';',
    '',
    '  const K = window.KotOR;',
    '  const GS = K && K.GameState;',
    '  const report = {',
    '    module: NAME, ok: false, phase: "start", ms: 0,',
    '    counts: {}, findings: [], skipped: [], truncated: {},',
    '  };',
    '  const now = () => (performance && performance.now) ? performance.now() : Date.now();',
    '  const t0 = now();',
    '  const elapsed = () => Math.round(now() - t0);',
    '  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));',
    '',
    '  const seenCounts = {};',
    '  const add = (code, severity, detail, subject) => {',
    '    seenCounts[code] = (seenCounts[code] || 0) + 1;',
    '    if (seenCounts[code] > CAP) { report.truncated[code] = seenCounts[code]; return; }',
    '    report.findings.push({',
    '      code: code, severity: severity,',
    '      detail: String(detail).slice(0, 400),',
    '      subject: subject == null ? null : String(subject).slice(0, 120),',
    '    });',
    '  };',
    '  const skip = (probeName, error) => {',
    '    report.skipped.push({',
    '      probe: probeName,',
    '      error: String((error && error.message) || error).slice(0, 300),',
    '    });',
    '  };',
    '  // A throw inside a probe is a skip, not a defect - see rule 2.',
    '  const probe = async (probeName, fn) => {',
    '    try { await fn(); } catch (error) { skip(probeName, error); }',
    '  };',
    '  // Reads one field defensively; used wherever a finding depends on engine internals.',
    '  const attempt = (fn, fallback) => { try { return fn(); } catch (e) { return fallback; } };',
    '  const THREW = "__probe_threw__";',
    '  const nameOf = (o) => attempt(function () {',
    '    return String(o.getName() || o.getTag() || o.templateResRef || "?");',
    '  }, "?");',
    '',
    '  if (!K || !GS) {',
    '    report.phase = "bootstrap";',
    '    add("engine-missing", "blocker", "window.KotOR.GameState is not present", null);',
    '    report.ms = elapsed();',
    '    return report;',
    '  }',
    '',
    '  // --- load ---------------------------------------------------------------',
    '  // A module whose load threw leaves loadingModule latched true, and LoadModule',
    '  // returns immediately when it is. Without this reset one bad module turns every',
    '  // module after it into a silent no-op reporting the PREVIOUS module contents -',
    '  // a sweep that reads 80/82 green while measuring one area 80 times.',
    '  report.phase = "load";',
    '  GS.loadingModule = false;',
    '  attempt(function () { GS.MenuManager.ClearMenus(); }, undefined);',
    '',
    '  // Identity, not existence. The module from the previous sweep step (or from',
    '  // the save that established the party) is still resident with a live area and',
    '  // loadingModule already false, so "an area exists" is true BEFORE this load',
    '  // even starts. The first run of this probe passed that check in 1.7s and',
    '  // reported zero rooms, zero creatures and zero of everything else - it had',
    '  // measured a module mid-teardown and called it a blocker. Hold a reference to',
    '  // the outgoing module and require a DIFFERENT one, fully built.',
    '  const previousModule = GS.module;',
    '',
    '  let loadThrew = null;',
    '  Promise.resolve(GS.LoadModule(NAME)).catch((e) => {',
    '    loadThrew = String((e && e.stack) || e);',
    '  });',
    '',
    '  const deadline = Date.now() + LOAD_TIMEOUT;',
    '  let ready = false;',
    '  while (Date.now() < deadline) {',
    '    if (loadThrew) break;',
    '    if (attempt(function () {',
    '      return !!GS.module',
    '        && GS.module !== previousModule',
    '        && GS.loadingModule === false',
    '        // Set on the last line of the LoadModule success path, after',
    '        // initAreaObjects. Nothing earlier means the area is fully built.',
    '        && GS.module.readyToProcessEvents === true',
    '        && !!GS.module.area;',
    '    }, false)) { ready = true; break; }',
    '    await sleep(500);',
    '  }',
    '',
    '  if (loadThrew) {',
    '    add("module-load-threw", "blocker", loadThrew, NAME);',
    '    report.ms = elapsed();',
    '    return report;',
    '  }',
    '  if (!ready) {',
    '    add("module-load-timeout", "blocker",',
    '      "module did not settle within " + LOAD_TIMEOUT + "ms", NAME);',
    '    report.ms = elapsed();',
    '    return report;',
    '  }',
    '',
    '  // Loading continues asynchronously past readyToProcessEvents - models and',
    '  // textures resolve on later frames. Probing immediately reports absences that',
    '  // fill themselves in a moment later, which would bury the real findings under',
    '  // false ones.',
    '  await sleep(SETTLE_MS);',
    '',
    '  const area = GS.module.area;',
    '',
    '  // The engine can land somewhere other than where it was asked to go. Silently',
    '  // probing whatever loaded would attribute one module findings to another.',
    '  const landed = attempt(function () { return String(GS.module.filename || "").toUpperCase(); }, "");',
    '  if (landed && landed !== NAME.toUpperCase()) {',
    '    add("module-identity-mismatch", "blocker",',
    '      "asked for " + NAME + " but the engine loaded " + landed, NAME);',
    '  }',
    '  report.landedAs = landed || null;',
    '',
    '  // --- inventory of what loaded -------------------------------------------',
    '  report.phase = "counts";',
    '  await probe("counts", async function () {',
    '    const collections = ["rooms", "creatures", "doors", "placeables", "triggers",',
    '      "waypoints", "sounds", "stores", "encounters", "items"];',
    '    for (const key of collections) {',
    '      const value = area[key];',
    '      report.counts[key] = Array.isArray(value) ? value.length : null;',
    '    }',
    '    if (!report.counts.rooms) {',
    '      // Some modules are transition stubs: you enter, a timed script fires',
    '      // LoadModule for somewhere else, and the engine correctly disposes the',
    '      // area it just built. 005EBO is one - it warps to 107PER on enter, and',
    '      // measuring afterwards finds a disposed husk with zero of everything.',
    '      // Reporting that as a blocker blamed the engine for doing the right',
    '      // thing, so establish which it is before calling it a defect.',
    '      let movedOn = false;',
    '      const until = Date.now() + 20000;',
    '      while (Date.now() < until) {',
    '        const now = attempt(function () {',
    '          return String(GS.module.filename || "").toUpperCase();',
    '        }, "");',
    '        if (attempt(function () { return !!GS.loadingModule; }, false)',
    '            || (now && now !== NAME.toUpperCase())) { movedOn = true; break; }',
    '        await sleep(500);',
    '      }',
    '      if (movedOn) {',
    '        report.transitionedAwayTo = attempt(function () {',
    '          return String(GS.module.filename || "");',
    '        }, null);',
    '        add("module-transitions-on-enter", "cosmetic",',
    '          "module warps elsewhere on enter; its own area is torn down by design",',
    '          NAME);',
    '      } else {',
    '        add("area-has-no-rooms", "blocker", "area loaded with zero rooms", NAME);',
    '      }',
    '    }',
    '  });',
    '',
    '  // --- geometry -----------------------------------------------------------',
    '  report.phase = "rooms";',
    '  await probe("rooms", function () {',
    '    const rooms = Array.isArray(area.rooms) ? area.rooms : [];',
    '    let modelless = 0;',
    '    for (const room of rooms) {',
    '      if (!attempt(function () { return !!room.model; }, false)) {',
    '        modelless += 1;',
    '        add("room-model-missing", "major", "room has no loaded model",',
    '          attempt(function () { return room.roomName || room.name; }, "?"));',
    '      }',
    '    }',
    '    report.counts.roomsWithoutModel = modelless;',
    '  });',
    '',
    '  // --- world objects ------------------------------------------------------',
    '  // Model, name and template are the three things every downstream system',
    '  // assumes. A creature with no model is the med-bay invisible-player class;',
    '  // a name carrying raw tokens is the designer-comment class.',
    '  const objectPasses = [',
    '    ["creatures", "creature"], ["doors", "door"], ["placeables", "placeable"],',
    '  ];',
    '  for (const pass of objectPasses) {',
    '    const key = pass[0], label = pass[1];',
    '    report.phase = key;',
    '    await probe(key, function () {',
    '      const list = Array.isArray(area[key]) ? area[key] : [];',
    '      let noModel = 0;',
    '      for (const object of list) {',
    '        if (!attempt(function () { return !!object.model; }, false)) {',
    '          noModel += 1;',
    '          add(label + "-model-missing", "major", "object has no loaded model", nameOf(object));',
    '        }',
    '        const named = attempt(function () { return object.getName(); }, THREW);',
    '        const resref = attempt(function () { return object.templateResRef; }, "?");',
    '        if (named === THREW) {',
    '          add(label + "-name-threw", "major", "getName() threw", resref);',
    '        } else if (typeof named === "string" && /<[A-Za-z][^>]*>/.test(named)) {',
    '          add(label + "-name-unresolved", "minor",',
    '            "name carries raw tokens: " + named, resref);',
    '        }',
    '        if (!attempt(function () { return !!object.templateResRef; }, false)) {',
    '          add(label + "-template-missing", "minor", "no templateResRef", nameOf(object));',
    '        }',
    '      }',
    '      report.counts[key + "WithoutModel"] = noModel;',
    '    });',
    '  }',
    '',
    '  // --- item properties ----------------------------------------------------',
    '  // Targets the class behind "Invalid Item Property Sub Type: undefined" and the',
    '  // absent-UpgradeType defect: an item whose properties array is missing, or whose',
    '  // entries do not resolve, silently disables everything the item grants.',
    '  report.phase = "items";',
    '  await probe("items", function () {',
    '    const seen = new Set();',
    '    let inspected = 0, faulted = 0;',
    '    const inspect = (item, owner) => {',
    '      if (!item || seen.has(item)) return;',
    '      seen.add(item);',
    '      inspected += 1;',
    '      const properties = attempt(function () { return item.properties; }, undefined);',
    '      if (!Array.isArray(properties)) {',
    '        faulted += 1;',
    '        add("item-properties-missing", "major", "item has no properties array",',
    '          nameOf(item) + " @ " + owner);',
    '        return;',
    '      }',
    '      for (const property of properties) {',
    '        const propertyName = attempt(function () { return property.propertyName; }, undefined);',
    '        if (propertyName === undefined || propertyName === null) {',
    '          faulted += 1;',
    '          add("item-property-unresolved", "major",',
    '            "property did not resolve (propertyName=" + String(propertyName) + ")",',
    '            nameOf(item) + " @ " + owner);',
    '        }',
    '      }',
    '    };',
    '',
    '    for (const creature of (Array.isArray(area.creatures) ? area.creatures : [])) {',
    '      const owner = nameOf(creature);',
    '      const equipment = attempt(function () { return creature.equipment; }, null);',
    '      if (equipment) {',
    '        for (const slot of Object.keys(equipment)) inspect(equipment[slot], owner);',
    '      }',
    '      const inventory = attempt(function () { return creature.inventory; }, null);',
    '      if (Array.isArray(inventory)) for (const item of inventory) inspect(item, owner);',
    '    }',
    '    for (const item of (Array.isArray(area.items) ? area.items : [])) inspect(item, "area");',
    '    report.counts.itemsInspected = inspected;',
    '    report.counts.itemsFaulted = faulted;',
    '  });',
    '',
    '  // --- dialogue -----------------------------------------------------------',
    '  // DLGObject is not exported from the bundle, so the probe cannot force-load a',
    '  // .dlg by resref. It tests something better anyway: what the engine ITSELF',
    '  // resolved. A creature whose template declares a Conversation but whose',
    '  // .conversation is absent is a creature the player can walk up to and get',
    '  // nothing from - a progression blocker that stays invisible until someone',
    '  // tries to talk to it.',
    '  report.phase = "dialogue";',
    '  await probe("dialogue", function () {',
    '    let declared = 0, resolved = 0, unresolved = 0;',
    '    for (const creature of (Array.isArray(area.creatures) ? area.creatures : [])) {',
    '      const resref = attempt(function () {',
    '        const root = creature.template && creature.template.RootNode;',
    '        if (!root || !root.hasField || !root.hasField("Conversation")) return "";',
    '        const field = root.getFieldByLabel("Conversation");',
    '        return field ? String(field.getValue() || "") : "";',
    '      }, "");',
    '      if (!resref) continue;',
    '      declared += 1;',
    '      const conversation = attempt(function () { return creature.conversation; }, null);',
    '      if (!conversation) {',
    '        unresolved += 1;',
    '        add("dialogue-unresolved", "major",',
    '          "creature declares conversation " + resref + " but none resolved",',
    '          nameOf(creature));',
    '        continue;',
    '      }',
    '      resolved += 1;',
    '      const entries = attempt(function () { return conversation.entries; }, null);',
    '      if (Array.isArray(entries) && entries.length === 0) {',
    '        add("dialogue-empty", "minor",',
    '          "conversation resolved with zero entries", resref);',
    '      }',
    '    }',
    '    report.counts.dialoguesDeclared = declared;',
    '    report.counts.dialoguesResolved = resolved;',
    '    report.counts.dialoguesUnresolved = unresolved;',
    '  });',
    '',
    '  // --- frames -------------------------------------------------------------',
    '  // Load-time correctness is not run-time correctness. Rendering a handful of',
    '  // frames catches the class that builds fine and throws on use - the class that',
    '  // previously only surfaced when a human opened the menu.',
    '  report.phase = "frames";',
    '  await probe("frames", async function () {',
    '    const errors = [];',
    '    const onError = (event) => {',
    '      errors.push(String((event && event.error && event.error.stack) ||',
    '        (event && event.message) || event));',
    '    };',
    '    window.addEventListener("error", onError);',
    '    try {',
    '      for (let i = 0; i < FRAMES; i += 1) {',
    '        await new Promise((resolve) => requestAnimationFrame(() => resolve()));',
    '      }',
    '    } finally {',
    '      window.removeEventListener("error", onError);',
    '    }',
    '    report.counts.framesRendered = FRAMES;',
    '    for (const error of errors.slice(0, CAP)) {',
    '      add("frame-exception", "critical", error, NAME);',
    '    }',
    '  });',
    '',
    '  report.phase = "complete";',
    '  report.ok = report.findings.filter((f) => f.severity === "blocker").length === 0;',
    '  report.ms = elapsed();',
    '  return report;',
    '})()',
  ].join('\n');
}

module.exports = { buildModuleProbeSource, PER_CODE_CAP, DEFAULT_SETTLE_MS };
